business_registration/urls.py
# business_registration/urls.py
from django.urls import path
from . import views
app_name = "business"
urlpatterns = [
    path('register/', views.register_business, name='register_business'),
    path('businesses/', views.business_list, name='business_list'),
    path('business/<int:business_id>/', views.business_detail, name='business_detail'),
    path('productregistration/', views.registerproduct, name='registerproduct'),
]

e_shop/urls.py
"""
URL configuration for e_shop project.

This file defines the URL patterns for the e_shop project. URLs are mapped to views
which handle incoming requests and return the appropriate response.

For more information on URL routing in Django, please refer to the official documentation:
https://docs.djangoproject.com/en/5.0/topics/http/urls/
"""

from django.contrib import admin
from django.urls import path, include  # Imports for URL routing
from . import settings  # Import project settings
from django.conf.urls.static import static  # Function for serving static files


# Import views from the e_shop1 app
from e_shop1 import views

urlpatterns = [
    
    path('admin/', admin.site.urls),# Admin site URL
    path('', views.index, name="index"),# Main website index view
    path('', include('e_shop1.urls')),  # Include e_shop1 app URLs
    path('business-registration/', include('business_registration.urls', namespace="business")),# Include URLs from the business_registration app with a namespace
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)# Serve static files in development mode (remove for production)

e_shop1/urls.py
# Defines URL patterns for the e_shop1 app.

from django.urls import path, include
from . import views

app_name = 'e_shop1'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    # Category related URLs
    path('category/<str:category_id>', views.singlecategory, name='category'),
    path('categories/', views.categories, name='categories'),

    # Search functionality
    path('search/', views.search, name='search'),

    # Business listing
    path('businesses/', views.businesses, name='businesses'),

    # About page
    path('about/', views.about, name='about'),

    # Product listing
    path('product/', views.products, name='products'),

    # User authentication URLs
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),

    # Product details page with dynamic product ID
    path('productdetail/<str:pk>', views.productdetail, name='productdetail'),

    # Checkout page
    path('checkout/', views.checkout, name='checkout'),

    # Shopping cart functionalities
    path('cart/', views.cart, name='cart'),
    path('update/', views.cart_update,name='cart_update'),

    # Product review and rating URLs
    path('review/<int:product_id>',views.postReview, name= "add review"),
    path('rate/<int:product_id>',views.postRating, name= "add rating"),
]

e_shop1/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import  forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'category', 'stock_quantity', 'prodimage', 'business']
        widgets = {
            'businesses': forms.CheckboxSelectMultiple,  # Use CheckboxSelectMultiple widget for selecting multiple businesses
        }

class SignUpForm(UserCreationForm):
	email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
	first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
	last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].widget.attrs['placeholder'] = 'User Name'
		self.fields['username'].label = ''
		self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['placeholder'] = 'Password'
		self.fields['password1'].label = ''
		self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

		self.fields['password2'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
		self.fields['password2'].label = ''
		self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'

e_shop1/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from .models import *
from django.contrib.auth import authenticate, login, logout 
from django.contrib import messages
from .forms import SignUpForm
import json, math
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from business_registration.models import Business
from e_shop1.models import Product
import math

# Create your views here.
def index(request):
    """View function for the home page."""
    products = Product.objects.all()
    categories = Category.objects.all()
    return render(request, 'e_shop1/index.html', {"products": products, "categories": categories})
    


def businesses(request):
    businesses = Business.objects.all()
    return render(request, 'e_shop1/businesses.html', {'businesses': businesses})


def products(request):
    """Show all products"""
    products = Product.objects.all()
    return render(request, 'e_shop1/product.html', { 'products' : products})


def categories(request):
    """Show all categories"""
    categories = Category.objects.all()
    return render(request, 'e_shop1/categories.html', {'categories': categories})

def singlecategory(request, category_id):
    """Show single category"""
    category = Category.objects.get(id = category_id)
    products = Product.objects.filter(category=category)
    return render(request, 'e_shop1/singlecategory.html', {'categories': categories,'products':products})


def about(request):
    return render(request, 'e_shop1/about.html', {})

def login_user(request):
   if request.method == "POST":
       username =request.POST.get('username')
       password = request.POST.get('password')
       user = authenticate(request , username=username, password=password)
       if user is not None:
           login(request, user)
           messages.success(request, ("Logged in successfully! Welcome to E-Shop"))
           return redirect('e_shop1:index')
       else:
           messages.warning(request, ('Username or Password is incorrect'))
           return redirect('e_shop1:login')
   else:
        return render(request, 'e_shop1/login.html', {}) 

def logout_user(request):
    logout(request)
    messages.success(request, ("Logged out successfully!"))
    return redirect('e_shop1:index') 

def register_user(request):
    form = SignUpForm()
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ("You have registered successfully! Welcome to E-shop!"))
            return redirect('e_shop1:index')
        
        else:
            messages.success(request, ("Whoops!, There was a problem Registering!, please try again."))
            return redirect('e_shop1:register')

    else:    
        return render(request, 'e_shop1/register.html', {'form': form })

def productdetail(request,pk ):
    """View function for the home page."""
    products = Product.objects.get(id=pk)
    ratings =  Rating.objects.filter(product=products)
    reviews = Review.objects.filter(product=products)
   

    if len(ratings) !=0 :
        average_rating = sum([x.get_value for x in ratings])/len(ratings)
        average_rating = math.ceil(average_rating)
        rating_list = [i for i in range(average_rating)]

    else:
        average_rating =0
        rating_list=[ ]  
    
    return render(request, 'e_shop1/productdetail.html',{ 'product' : products, 'rating' : average_rating, 'rating_list' : rating_list, 'reviews' : reviews} )

def postReview(request, product_id):
    product = Product.objects.get(id=product_id)
    review = request.POST.get('review')
    new = Review.objects.create(
        product = product,
        user = request.user.customer,
        text = review
    )
    new.save()
    return redirect('e_shop1:productdetail', product_id)



def postRating(request, product_id):
    product = Product.objects.get(id=product_id)
    rating = request.POST.get('rate')
    new = Rating.objects.create(
        product = product,
        user = request.user.customer,
        value = rating
    )
    new.save()
    return redirect('e_shop1:productdetail', product_id)




def search(request):
    if request.method == 'GET':
        query = request.GET.get('query')

        if query:
            # Combined search across products, categories, and businesses
            results = Q(name__icontains=query)

            product_results = results |  Q(price__icontains=query)
            products = Product.objects.filter(product_results).distinct()
            

            # Search businesses by name, description, and location
            business_results = results | Q(location__icontains=query)
            businesses = Business.objects.filter(business_results).distinct()

            category_results = results |  Q(description__icontains=query)
            categories = Category.objects.filter(category_results).distinct()

            # Context dictionary with combined search results
            context = {
                'products': products,
                'categories': categories,
                'businesses': businesses,
            }

            return render(request, 'e_shop1/search.html', context)

        else:
            # Handle empty search query gracefully (optional)
            context = {'message': 'Please enter a search term.'}
            return render(request, 'e_shop1/search.html', context)

    else:
            print("Search could not be found")
            return request(request, 'e_shop1/search.html', {})
    



def cart(request):
    if request.user.is_authenticated:
        try:
            customer = request.user.customer
            order, created = Order.objects.get_or_create(customer=customer, complete=False)
            items = order.orderitem_set.all()
        except ObjectDoesNotExist:
            items = []
            order = {'get_cart_total': 0, 'get_cart_items': 0}
        context = {
            'items': items,
            'order': order,
        }
        return render(request, "e_shop1/cart1.html", context)
    else:
        messages.warning(request, 'You must login first!')
        return redirect('e_shop1:index')



def checkout(request):
    if request.user.is_authenticated:
        order, created = Order.objects.get_or_create(customer=request.user.customer, complete = False)
        items = order.orderitem_set.all()
    else:    
        items=[]
        order ={'get_cart_total':0,'get_cart_items':0}
    context = {'items':items, 
               'order':order}
    return render(request,"e_shop1/checkout.html", context)

def cart_update(request):  
    if request.user.is_authenticated:
        data = json.loads(request.body)
        productId = data['product_id']
        action = data['action']

        customer = Customer.objects.get(user=request.user)
        product = Product.objects.get(id=productId)
        order,created = Order.objects.get_or_create(customer=customer, complete=False)
        order_item,created = OrderItem.objects.get_or_create(order=order, product=product)
        if action == "add":

            order_item.quantity = (order_item.quantity+1)
            messages.success(request, 'Product added to cart')
        elif action == "remove":
            order_item.quantity = (order_item.quantity-1)
            messages.warning(request, 'Item removed from cart')

        order_item.save()

        if order_item.quantity <= 0:
            order_item.delete()

        return JsonResponse(action + ' complete', safe=False)
    else:
        messages.warning(request, 'You must login first!')
        return redirect('e_shop1:products')


    

        

e_shop1/templates/e_shop1/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>

    <div class="container-fluid">
      {% for message in messages%}
      
      <div class="row">
          <div class="col-xs-12">
              <div class="alert alert-success">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                      ×</button>
                 <span class="glyphicon glyphicon-ok"></span> <strong>Success Message</strong>
                  <hr class="message-inner-separator">
                  <p>
                      {{message}}</p>
              </div>
          </div>
        </div>
      </div>
    </div>
        {% endfor %}
    <title>E-shop</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">

    <link href="{% static 'css/open-iconic-bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    
    <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.theme.default.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet">
    


    

    <link href="{% static 'css/aos.css' %}" rel="stylesheet">

    <link href="{% static 'css/ionicons.min.css' %}" rel="stylesheet">
    
    <link href="{% static 'css/bootstrap-datepicker.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery.timepicker.css' %}" rel="stylesheet">
    
    <link href="{% static 'css/flaticon.css' %}" rel="stylesheet">
    <link href="{% static 'css/icomoon.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    

    <script>
      var user = '{{request.user}}'

      function getCookie(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want or not?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }
      const csrftoken = getCookie('csrftoken');
  </script>


  </head>


  
  <body class="goto-here">
  <section>
    <div class="py-1 bg-primary">
    <div class="container">
        <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
            <div class="col-lg-12 d-block">
                <div class="row d-flex">
                    <div class="col-md pr-4 d-flex topper align-items-center">
                        <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
                        <span class="text">+256 756831592</span>
                    </div>
                    <div class="col-md pr-4 d-flex topper align-items-center">
                        <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
                        <span class="text">eshoponline54@gmail.com</span>
                    </div>
                    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
                        <span class="text">working with you 24/7</span>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>



  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="{% url 'e_shop1:index' %}">E-shop</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation" >
        <span class="oi oi-menu"></span> Menu
      </button>

      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active"><a href="{% url 'e_shop1:index' %}" class="nav-link">Home</a></li>
          <li class="nav-item dropdown">
            {% if user.is_authenticated %}
              <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Browse</a>
              <div class="dropdown-menu" aria-labelledby="dropdown04">
                <a class="dropdown-item" href="{% url 'business:register_business' %}">Register Business</a>
                <a class="dropdown-item" href="{% url 'e_shop1:logout' %}">Logout</a>
                <a class="dropdown-item" href="{% url 'e_shop1:cart' %}">Cart</a>
                <a class="dropdown-item" href="{% url 'e_shop1:checkout' %}">Checkout</a>  
              </div>
            {% else %}
              <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Login/Register</a>
              <div class="dropdown-menu" aria-labelledby="dropdown04">
                <a class="dropdown-item" href="{% url 'e_shop1:login' %}">Login</a>
                <a class="dropdown-item" href="{% url 'e_shop1:register' %}">Register</a>
              </div>
            {% endif %}
          </li>
          <li class="nav-item"><a href="{% url 'e_shop1:about' %}" class="nav-link">About</a></li>
          <li class="nav-item"><a href="{% url 'e_shop1:products' %}" class="nav-link">Products</a></li>
          <li class="nav-item"><a href="{% url 'e_shop1:categories' %}" class="nav-link">Categories</a></li>
          <li class="nav-item"><a href="{% url 'business:business_list' %}" class="nav-link">Businesses</a></li>
          <li class="nav-item cta cta-colored"><a href="{% url 'e_shop1:cart' %}" class="nav-link"><span class="icon-shopping_cart"></span><span id="cart-quantity" >[{{request.user.customer.sum_cart}}]</span></a></li>
        </ul>
        <form class="d-flex" method="get" action="{% url 'e_shop1:search' %}">
          {% csrf_token %}
          <input class="form-control me-0" type="text" name="query" placeholder="Search product, category, businesses..." aria-label="Search">
          <button class="btn btn-outline-success" type="submit"><span class="icon-search"></span></button>
        </form>
      </div>
    </div>
  </nav>
</section>

{% block content %} {% endblock %}


<footer class="ftco-footer ftco-section">
    <div class="container">
        <div class="row">
            <div class="mouse">
                      <a href="#" class="mouse-icon">
                          <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
                      </a>
                  </div>
        </div>
      <div class="row mb-5">
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">E-shop</h2>
            <p>At E-Shop, we offer trendsetting fashion, premium quality, and seamless shopping. </p>
            <p>Explore our curated collections, enjoy exclusive deals, and experience top-notch customer care. Join us today!</p>
            <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
              <li class="ftco-animate"><a href="https://www.twitter.com"><span class="icon-twitter"></span></a></li>
              <li class="ftco-animate"><a href="https://www.facebook.com"><span class="icon-facebook"></span></a></li>
              <li class="ftco-animate"><a href="https://www.instagram.com"><span class="icon-instagram"></span></a></li>
            </ul>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4 ml-md-5">
            <h2 class="ftco-heading-2">Menu</h2>
            <ul class="list-unstyled">
              <li><a href="{% url 'e_shop1:products' %}" class="py-2 d-block">Our products</a></li>
              <li><a href="{% url 'e_shop1:about' %}" class="py-2 d-block">About</a></li>
              <li><a href="#" class="py-2 d-block">Journal</a></li>
              <li><a href="#" class="py-2 d-block">Contact Us</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-4">
           <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">Help</h2>
            <div class="d-flex">
                <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
                  <li><a href="#" class="py-2 d-block">Purchacing Information</a></li>
                  <li><a href="#" class="py-2 d-block">Returns &amp; Exchange</a></li>
                  <li><a href="#" class="py-2 d-block">Terms &amp; Conditions</a></li>
                  <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                </ul>
                <ul class="list-unstyled">
                  <li><a href="#" class="py-2 d-block">FAQs</a></li>
                  <li><a href="#" class="py-2 d-block">Contact</a></li>
                </ul>
              </div>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Have a Questions?</h2>
              <div class="block-23 mb-3">
                <ul>
                  <li><span class="icon icon-map-marker"></span><span class="text">Makerere University, Makerere, Kampala, Uganda</span></li>
                  <li><a href="#"><span class="icon icon-phone"></span><span class="text">+256 756831592</span></a></li>
                  <li><a href="#"><span class="icon icon-envelope"></span><span class="text">eshoponline54@gmail.com</span></a></li>
                </ul>
              </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">

          <p>  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved |  by  <a href="{% url 'e_shop1:index' %}" target="_blank">E-shop</a></p>
        </div>
      </div>
    </div>
  </footer>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/cart.js' %}"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    
 
</body>
</html>

e_shop1/templates/e_shop1/logout.html
{% extends 'e_shop1/base.html'  %}


{% load static %}


<!--<div class="container">
 {% for message in messages%}
    <div class="col-sm-6 col-md-6">
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                ×</button>
            <span class="glyphicon glyphicon-record"></span> <strong>Warning Message</strong>
            <hr class="message-inner-separator">
            <p>
                Username or Password is incorrect
            </p>
        </div>
    </div>
{% endfor %}

</div>-->

e_shop1/templates/e_shop1/search.html
{% extends 'e_shop1/base.html' %}

{% block title %}Search{% endblock %}

{% block content %}
<div class="hero-wrap hero-bread" style= background-color:#4a985a;>
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'e_shop1:index' %}"><E-SHOP></a></span> <span>Search</span></p>
                <h1 class="mb-0 bread">Search Results</h1>
            </div>
        </div>
    </div>
</div>


<section class="ftco-section">
  {% if products %}
      <div class="container">
          <div class="row">
              {% for product in products %}
                  <div class="col-md-6 col-lg-3 ftco-animate">
                      <div class="product">
                          <img class="img-fluid" src="{{ product.prodimage.url }}" alt="{{ product.name }}" style="width: 740px; aspect-ratio: auto 740 / 300; height: 300px;">
                          <div class="overlay"></div>
                          <div class="text py-3 pb-4 px-3 text-center">
                              <h3><a href="#">{{ product.name }}</a></h3>
                              <div class="d-flex">
                                  <div class="pricing">
                                      <p class="price">UGX {{ product.price }}</p>
                                  </div>
                              </div>
                              <div class="m-auto d-flex justify-content-between">
                                  <button type="button" data-product="{{ product.id }}" class="btn btn-primary update-cart" dat-product="add">
                                      <i class="ion-ios-cart"></i> Add to Cart
                                  </button>
                                  <a href="{% url 'e_shop1:productdetail' product.id %}">
                                      <button class="btn btn-primary buy-now">
                                          <i class="ion-ios-menu"></i> View Details
                                      </button>
                                  </a>
                              </div>
                          </div>
                      </div>
                  </div>
              {% endfor %}
          </div>
      </div>
  {% endif %}

  {% if categories %}
      <div class="container">
          <div class="row justify-content-center">
              {% for category in categories %}
                  <div class="col-md-6 col-lg-3 ftco-animate">
                      <div class="product">
                          <a href="{% url 'e_shop1:category' category.id %}" class="img-prod">
                              <img class="img-fluid" src="{{ category.catimage.url }}" alt="{{ category.name }}" style="width: 740px; aspect-ratio: auto 740 / 300; height: 300px;">
                          </a>
                          <div class="overlay"></div>
                          <div class="text py-3 pb-4 px-3 text-center">
                              <h3><a href="{% url 'e_shop1:category' category.id %}">{{ category.name }}</a></h3>
                              <div class="d-flex"></div>
                          </div>
                      </div>
                  </div>
              {% endfor %}
          </div>
      </div>
  {% endif %}

  {% if businesses %}
    <div class="container">
        <div class="row">
            {% for business in businesses %}
            <div class="col-md-6 col-lg-4 ftco-animate">
                <div class="product">
                    {% if business.businessimage %}
                    <a href="#" class="img-prod">
                        <img class="img-fluid" src="{{ business.businessimage.url }}" alt="{{ business.name }}" style="width: 725px; aspect-ratio: auto 725 / 380; height: 380px;">
                        <div class="overlay"></div>
                        <h3><a href="{% url 'business:business_detail' business.id %} ">{{ business.name }}</a></h3>
                        <p>{{ business.location }}</p>
                        <p>Contact: {{ business.contact }}</p>
                    </a>
                    {% else %}
                    <div class="text py-3 pb-4 px-3 text-center">
                        <h3><a href="{% url 'business:business_detail' business.id %} ">{{ business.name }}</a></h3>
                        <p>{{ business.location }}</p>
                        <p>Contact: {{ business.contact }}</p>
                    </div>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
  {% endif %}
</section>


{% endblock %}