business_registration/urls.py
# business_registration/urls.py
from django.urls import path
from . import views
app_name = "business"
urlpatterns = [
    path('register/', views.register_business, name='register_business'),
    path('businesses/', views.business_list, name='business_list'),
    path('business/<int:business_id>/', views.business_detail, name='business_detail'),
    path('productregistration/', views.registerproduct, name='registerproduct'),
]

e_shop/urls.py
"""
URL configuration for e_shop project.

This file defines the URL patterns for the e_shop project. URLs are mapped to views
which handle incoming requests and return the appropriate response.

For more information on URL routing in Django, please refer to the official documentation:
https://docs.djangoproject.com/en/5.0/topics/http/urls/
"""

from django.contrib import admin
from django.urls import path, include  # Imports for URL routing
from . import settings  # Import project settings
from django.conf.urls.static import static  # Function for serving static files


# Import views from the e_shop1 app
from e_shop1 import views

urlpatterns = [
    
    path('admin/', admin.site.urls),# Admin site URL
    path('', views.index, name="index"),# Main website index view
    path('', include('e_shop1.urls')),  # Include e_shop1 app URLs
    path('business-registration/', include('business_registration.urls', namespace="business")),# Include URLs from the business_registration app with a namespace
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)# Serve static files in development mode (remove for production)

e_shop1/urls.py
# Defines URL patterns for the e_shop1 app.

from django.urls import path, include
from . import views

app_name = 'e_shop1'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    # Category related URLs
    path('category/<str:category_id>', views.singlecategory, name='category'),
    path('categories/', views.categories, name='categories'),

    # Search functionality
    path('search/', views.search, name='search'),

    # Business listing
    path('businesses/', views.businesses, name='businesses'),

    # About page
    path('about/', views.about, name='about'),

    # Product listing
    path('product/', views.products, name='products'),

    # User authentication URLs
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),

    # Product details page with dynamic product ID
    path('productdetail/<str:pk>', views.productdetail, name='productdetail'),

    # Checkout page
    path('checkout/', views.checkout, name='checkout'),

    # Shopping cart functionalities
    path('cart/', views.cart, name='cart'),
    path('update/', views.cart_update,name='cart_update'),

    # Product review and rating URLs
    path('review/<int:product_id>',views.postReview, name= "add review"),
    path('rate/<int:product_id>',views.postRating, name= "add rating"),
]

business_registration/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True)
    catimage = models.ImageField(upload_to='photos/', default=None)
    class Meta:
        verbose_name_plural = 'Categories'
    def __str__(self):
        return self.name
class Business(models.Model):
    name = models.CharField(max_length=100)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField()
    contact = models.CharField(max_length=11, blank=True)
    location = models.CharField(max_length=180)
    business_image = models.ImageField(upload_to='photos/', default=None ,unique=True, blank =True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='businesses')
    description = models.TextField(max_length=1000,blank=True)

    class Meta:
        verbose_name_plural = 'Registered Businesses'
    def __str__(self):
        return self.name

business_registration/forms.py
# registration/forms.py

from django import forms
from .models import Business
from e_shop1.models import Product

class BusinessRegistrationForm(forms.ModelForm):
    class Meta:
        model = Business
        fields = ['name',  'email', 'contact', 'location', 'business_image', 'category', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Business Name'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Business Description'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'contact': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Contact Number'}),
            'location': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Business Location'}),
            'business_image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'category': forms.Select(choices=(), attrs={'class': 'form-control'}),
        }



class ProductForm(forms.ModelForm):
  class Meta:
    model = Product
    fields = ['name', 'business', 'description', 'price', 'category', 'prodimage']
    widgets = {
        'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Product Name'}),
        'business': forms.Select(choices=(), attrs={'class': 'form-control'}),
        'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Product Description'}),
        'price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Price'}),
        'category': forms.Select(choices=(), attrs={'class': 'form-control'}),
        'prodimage': forms.ClearableFileInput(attrs={'class': 'form-control'}),

    }

business_registration/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import BusinessRegistrationForm, ProductForm
from .models import Business
from django.contrib import messages





def register_business(request):
    if request.method == 'POST':
        form = BusinessRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            business = form.save(commit=False)
            business.owner = request.user
            business.save()
            messages.success(request, ("You have registered successfully! Welcome to E-shop!"))
            return redirect('business:business_detail',business.id)
        else:
            messages.success(request, ("Whoops!, There was a problem Registering!, please try again."))
            return redirect('business_registration:register')
    else:
        form = BusinessRegistrationForm()
        return render(request, 'business_registration/register.html', {'form': form})


def business_list(request):
    businesses = Business.objects.all()
    return render(request, 'business_registration/businesses.html', {'businesses': businesses})


def registerproduct(request):

  if request.method == 'POST':
    form = ProductForm(request.POST, request.FILES)
    if form.is_valid():
      product = form.save(commit=False)
      product.save()
      
      return business_detail(request, product.business.id)

  else:
    form = ProductForm()

  return render(request, 'business_registration/productregister.html', {'form': form})

def business_detail(request, business_id):
  business = get_object_or_404(Business, id=business_id)
  products = business.products.filter(business=business)

  if business.owner == request.user:
        show_edit_and_add_product = True
  else:
        show_edit_and_add_product = False

  context = {
        'business': business,
        'products' :products,
        'show_edit_and_add_product': show_edit_and_add_product,
      }
  return render(request, 'business_registration/business_detail.html', context)

business_registration/templates/business_registration/business_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>

    <div class="container-fluid">
      {% for message in messages%}
      
      <div class="row">
          <div class="col-xs-12">
              <div class="alert alert-success">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                      ×</button>
                 <span class="glyphicon glyphicon-ok"></span> <strong>Success Message</strong>
                  <hr class="message-inner-separator">
                  <p>
                      {{message}}</p>
              </div>
          </div>
        </div>
      </div>
    </div>
        {% endfor %}
    <title>E-shop</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">
    
    
    
    <link href="{% static 'css/open-iconic-bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    
    <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.theme.default.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet">
    

    <link href="{% static 'css/aos.css' %}" rel="stylesheet">

    <link href="{% static 'css/ionicons.min.css' %}" rel="stylesheet">
    
    <link href="{% static 'css/bootstrap-datepicker.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery.timepicker.css' %}" rel="stylesheet">
    
    <link href="{% static 'css/flaticon.css' %}" rel="stylesheet">
    <link href="{% static 'css/icomoon.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
      <div class="container">
        <a class="navbar-brand" href="{% url 'e_shop1:index' %}">E-shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="oi oi-menu"></span> Menu
        </button>
  
        <div class="collapse navbar-collapse" id="ftco-nav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active"><a href="{% url 'e_shop1:index' %}" class="nav-link">Home</a></li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Browse</a>
            <div class="dropdown-menu" aria-labelledby="dropdown04">
                  {% if user.is_authenticated %}
                      <a class="dropdown-item" href="{% url 'business:register_business' %}">Register Business</a>
  
                      <a class="dropdown-item" href="{% url 'e_shop1:logout' %}">logout</a>  
                  {% else %}
                      <a class="dropdown-item" href="{% url 'e_shop1:login' %}">login</a>
                      <a class="dropdown-item" href="{% url 'e_shop1:register' %}">register</a>
                  {% endif %}
                
  
              <a class="dropdown-item" href="{% url 'e_shop1:cart' %}">Cart</a>
              <a class="dropdown-item" href="{% url 'e_shop1:checkout' %}">Checkout</a>
            </div>
            
          </li>
            <li class="nav-item"><a href="{% url 'e_shop1:about' %}" class="nav-link">About</a></li>
            <li class="nav-item"><a href="{% url 'e_shop1:products' %}" class="nav-link">Products</a></li>
            <li class="nav-item"><a href="{% url 'e_shop1:categories' %}" class="nav-link">Categories</a></li>
            <li class="nav-item"><a href="{% url 'business:business_list' %}" class="nav-link">Businesses</a></li>
            <li class="nav-item cta cta-colored"><a href="{% url 'e_shop1:cart' %}" class="nav-link"><span class="icon-shopping_cart"></span><span id="cart-quantity" >
              [{{request.user.customer.sum_cart}}]
  
            </span></a></li>
  
  
            <form class="d-flex" method="get" action="{% url 'e_shop1:search' %}">
              {% csrf_token %}
              
                  <input class="form-control me-0" type="text" name="query" placeholder="Search product, category, businesses..." aria-label="Search">
                  <button class="btn btn-outline-success" type="submit" >
                      <span class="icon-search"></span>
                
              </div>
          </form>
        
          </ul>
        </div>
      </div>
    </nav>
  </head>

      
      <body>

        <header class="d-flex flex-row bg-green rounded-top py-2 px-3" style="background-color: rgb(248, 246, 246);">

          <div class="w-1/4">  <img src="{{ business.business_image.url }}" alt="Business Image" class="img-fluid img-thumbnail rounded-square mx-auto d-block" style="width: 150px; height: 150px;">
          </div>
          <div class="flex-grow-1 ms-4">
            <h4>Business name: {{ business.name }}</h4>
            <h4>Location: {{ business.location }}</h4>
            <h4>Category: {{ business.category }}</h4>
          </div>
          
          {% with business=request.user.business %}
          <div class="ms-3">
            {% if show_edit_and_add_product %}
            <!-- <button type="button" class="btn btn-outline-grey">Edit profile</button> -->
            <a href="{% url 'business:registerproduct' %}" button type="button" class="btn btn-outline-grey">Add Product</a>
            {% endif %}
          </div>
          {% endwith %}
          
        </header>
                

              
        <div class="container p-4" style="margin-left: 0%;">
          <h3 class="lead fw-normal mb-1">About Business</h3>
          <div class="row">
            <div class="col-md-12">
              <p class="text-justify"> {{ business.description }} </p>
            </div>
          </div>
        </div>

        <div class="container p-4" style="margin-left: 0%;">
          <h2 class="lead fw-normal mb-1">Business Products</h2>
         
        </div>


        {% for product in products %} {% if product.business.id == business.id %}

            <div class="col-md-6 col-lg-3 ftco-animate">
              <div class="product">
                <img class="img-fluid" src="{{ product.prodimage.url }}" alt="{{ product.name }}"  style="width: 740px; aspect-ratio: auto 740 / 300; height: 300px;">
                <div class="overlay"></div>
                <div class="text py-3 pb-4 px-3 text-center">
                  <h3><a href="#">{{ product.name }}</a></h3>
                  <div class="d-flex">
                    <div class="pricing">
                      <p class="price">UGX {{ product.price }}</p>
                    </div>
                  </div>
                  
                  <div class="m-auto d-flex justify-content-between">
                    <button type="button" value="{{  product.id }}" class="update-cart btn btn-primary " data-product="{{product.id}}" id= "add-to-cart" data-action="add" >
                      <i class="ion-ios-cart"></i> Add to Cart
                    </button>
                    
                    <a href="{% url 'e_shop1:productdetail' product.id %}">
                      <button class="btn btn-primary buy-now">
                        <i class="ion-ios-menu"></i> View Details
                      </button>
                    </a>
                  </div>
      
                </div>
              </div>
            </div>
            {% endif %}{% endfor %}
          </div>
        </section>
        
        

        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
        <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
        <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'js/aos.js' %}"></script>
        <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
        <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
        <script src="{% static 'js/scrollax.min.js' %}"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
        <script src="{% static 'js/google-map.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/cart.js' %}"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
            

  </body>

</html>

business_registration/templates/business_registration/businesses.html
{% extends 'e_shop1/base.html' %}

{% block title %}Businesses{% endblock %}

{% block content %}
<div class="hero-wrap hero-bread" style= background-color:#4a985a;>
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'e_shop1:index' %}">E-SHOP</a></span> <span>Businesses</span></p>
                <h1 class="mb-0 bread">Available Businesses</h1>
            </div>
        </div>
    </div>
</div>

<section class="ftco-section">
    <div class="container">
        <div class="row">
            {% for business in businesses %}
            <div class="col-md-6 col-lg-4 ftco-animate">
                <div class="product">
                    {% if business.business_image %}
                    <a href="#" class="img-prod">
                        <img class="img-fluid" src="{{ business.business_image.url }}" alt="{{ business.name }}" style="width: 725px; aspect-ratio: auto 725 / 380; height: 380px;">
                        <div class="overlay"></div>
                        <h3><a href="{% url 'business:business_detail' business.id %} ">{{ business.name }}</a></h3>
                        <p>{{ business.location }}</p>
                        <p>Contact: {{ business.contact }}</p>
                    </a>
                    {% else %}
                    <div class="text py-3 pb-4 px-3 text-center">
                        <h3><a href="{% url 'business:business_detail' business.id %} ">{{ business.name }}</a></h3>
                        <p>{{ business.location }}</p>
                        <p>Contact: {{ business.contact }}</p>
                    </div>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

business_registration/templates/business_registration/productregister.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>E-shop</title>

    <link href="{% static 'css/open-iconic-bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    
    <script src="https://cdn.jsdelivr.net.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
</head>
<body style="background-color: #f8f9fa;">

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">Product Registration</h2>
                
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <button type="submit" class="btn-primary btn-sm w-10 text-center ">Add Product</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

business_registration/templates/business_registration/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>E-shop</title>

    <link href="{% static 'css/open-iconic-bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    
    <script src="https://cdn.jsdelivr.net.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
</head>
<body style="background-color: #f8f9fa;">

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">Business Registration</h2>
                    <p class="card-text text-center lead mb-4" style="font-size: 14px;">Register your business and become our official partner. Your business will enjoy mind-blowing success with our top-notch marketing team, 99.9999% availability, and unrivaled online presence.</p>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        
                        <button type="submit" class="btn-primary btn-sm w-10 text-center ">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>